modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GENERAL PUBLIC LICENSE"
[[mods]] #mandatory
modId= "t0001" #mandatory
version="0.00.5" #mandatory
displayName="T0001" #mandatory
authors="sidtheplayer" #optional
description='''Ligma Ligma boy Ligma boy, wait those are wrong lyri-'''

[[dependencies.t0001]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47.4.0,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.t0001]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.t0001]]
modId="photon"
mandatory=true
versionRange="[1.1.14,)"
ordering="NONE"
side="BOTH"
